######################################################################
# Automatically generated by qmake (3.1) Sun Feb 26 15:27:34 2017
######################################################################

QT += core gui widgets
TEMPLATE = app
TARGET = pathing
INCLUDEPATH += .

# Input
HEADERS += \
           data.h \
           mainwgt.h \
    cell.h \
    cellg.h

SOURCES += \
           data.cpp \
           main.cpp \
           mainwgt.cpp \
    cell.cpp \
    cellg.cpp


